Repository wecode-bootcamp-korea/14-2nd-AirBitAndByte-frontend, pull requests merged in 2020-12, with the labels that each got.

#4 [고은정] add: property gallery 모달창 구현
  .gitignore
  package-lock.json
  package.json
  public/Data/response.json
  public/data/propertyImages.json
  public/favicon.ico
  public/images/IMG_7746.JPG
  public/images/airBnB_black.png
  public/images/airBnB_black.svg
  public/images/airBnB_pink.png
  public/images/airBnB_pink.svg
  public/images/airBnB_vertical_black.png
  public/images/airBnB_vertical_black.svg
  public/images/airBnB_vertical_pink.png
  public/images/airBnB_vertical_pink.svg
  public/images/air_pink_logo (1).png
  public/images/air_pink_logo.png
  public/images/air_pink_logo.svg
  public/images/defaultProfile.png
  public/images/hostProfile.jpg
  public/images/property1.png
  public/images/property2.png
  public/images/property3.png
  public/images/property4.png
  public/images/property5.png
  public/images/property6.png
  public/images/propertyCalender.png
  public/images/propertyGraph.png
  public/images/propertyMap.png
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.scss
  src/components/Property/GalleryModal.jsx
  src/components/Property/Property.jsx
  src/components/Property/Property.scss
  src/components/Property/PropertyCalender.jsx
  src/components/Property/PropertyDetail.jsx
  src/components/Property/PropertyGallery.jsx
  src/components/Property/PropertyMap.jsx
  src/components/Property/PropertyReview.jsx
  src/config.js
  src/index.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/GlobalStyles.js
  src/styles/common.scss
  src/styles/reset.scss
  src/styles/theme.js
Labels: Status: 리뷰 요청

#5 [고은정] add: 구글 소셜 로그인 구현
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/Routes.js
  src/components/Nav/Login.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Signup.jsx
  src/components/Nav/SignupEmail.jsx
  src/config.js
  src/index.js
  src/service/auth_service.js
  src/service/firebase.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#3 [장재원] add : Nav Footer / main page UI 완성
  package.json
  public/images/airBnBlogo.svg
  public/images/mainImage/allType.jpg
  public/images/mainImage/animalHouse.jpg
  public/images/mainImage/busan.jpg
  public/images/mainImage/comfortable.jpg
  public/images/mainImage/daegu.jpg
  public/images/mainImage/daejeon.jpg
  public/images/mainImage/gwangju.jpg
  public/images/mainImage/happy.jpg
  public/images/mainImage/jeju.jpg
  public/images/mainImage/nomad.jpg
  public/images/mainImage/seoul.jpg
  public/images/mainImage/specialHouse.jpg
  public/images/mainImage/suwon.jpg
  public/images/mainImage/tourism.jpg
  public/images/mainImage/woodHouse.jpg
  public/images/mainImage/yeosu.jpg
  public/images/mainimage.jpeg
  public/images/minus.svg
  public/images/plus.svg
  public/index.html
  src/Pages/Main/Main.jsx
  src/Pages/Main/RecommendedPlaces.jsx
  src/Routes.js
  src/components/Footer/Footer.jsx
  src/components/Footer/FooterList.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/NavSearchInfo.jsx
  src/components/Nav/NavSearchModal.jsx
  src/pages/Main/Main.js
  src/styles/GlobalStyles.js
  yarn.lock
Labels: Status: 리뷰 요청

#6 [고은정] add: calendar 컴포넌트 구현
  .env
  package-lock.json
  package.json
  public/data/property.json
  public/index.html
  src/Routes.js
  src/components/Nav/Login.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Signup.jsx
  src/components/Nav/SignupEmail.jsx
  src/components/Property/GalleryModal.jsx
  src/components/Property/NavProperty.jsx
  src/components/Property/Property.jsx
  src/components/Property/PropertyCalender.jsx
  src/components/Property/PropertyDetail.jsx
  src/components/Property/PropertyGallery.jsx
  src/components/Property/PropertyHost.jsx
  src/components/Property/PropertyMap.jsx
  src/components/Property/PropertyOthers.jsx
  src/components/Property/PropertyReservation.jsx
  src/components/Property/PropertyReview.jsx
  src/components/Property/PropertyReviewModal.jsx
  src/config.js
  src/styles/theme.js
Labels: Status: Accepted

#7 [고은정] add: 좋아요 기능 및 좋아요 페이지 구현
  .gitignore
  package-lock.json
  package.json
  public/data/property.json
  src/Routes.js
  src/components/Nav/Login.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/NavSearchInfo.jsx
  src/components/Nav/Signup.jsx
  src/components/Nav/SignupEmail.jsx
  src/components/Property/GalleryModal.jsx
  src/components/Property/Property.jsx
  src/components/Property/PropertyCalender.jsx
  src/components/Property/PropertyDetail.jsx
  src/components/Property/PropertyGallery.jsx
  src/components/Property/PropertyHost.jsx
  src/components/Property/PropertyMap.jsx
  src/components/Property/PropertyOthers.jsx
  src/components/Property/PropertyReservation.jsx
  src/components/Property/PropertyReview.jsx
  src/components/Property/PropertyReviewModal.jsx
  src/config.js
  src/index.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#8 [장재원] ADD : property list 세팅 ui 구현
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/LIST_MOCK_DATA.json
  src/Pages/PlaceList/PlaceListItem.jsx
  src/Routes.js
  src/components/Nav/Nav.jsx
  src/config.js
  src/pages/PlaceList/PlaceFilter.jsx
  src/pages/PlaceList/PlaceList.jsx
  src/pages/PlaceList/PlaceListMap.jsx
  yarn.lock
Labels: Status: 리뷰 요청

#9 [고은정] add: login redux store 기능 추가
  .gitignore
  package-lock.json
  package.json
  public/data/LIST_MOCK_DATA.json
  public/data/property.json
  public/images/avatar0.png
  public/images/avatar1.png
  public/images/avatar2.png
  public/images/avatar3.png
  public/images/avatar4.png
  public/images/avatar5.png
  public/images/avatar6.png
  src/components/Nav/Login.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/Signup.jsx
  src/components/Nav/SignupEmail.jsx
  src/components/Property/GalleryModal.jsx
  src/components/Property/Property.jsx
  src/components/Property/PropertyCalender.jsx
  src/components/Property/PropertyDetail.jsx
  src/components/Property/PropertyGallery.jsx
  src/components/Property/PropertyHost.jsx
  src/components/Property/PropertyOthers.jsx
  src/components/Property/PropertyReservation.jsx
  src/components/Property/PropertyReview.jsx
  src/components/Property/PropertyReviewModal.jsx
  src/config.js
  src/index.js
  src/store/actions/index.js
  src/store/reducers/index.js
  src/store/reducers/loginReducer.js
Labels: Status: 리뷰 요청

#11 [고은정] add: 결제 페이지 및 네비바 유저 모달창 추가
  README.md
  package-lock.json
  public/images/air_pink_logo_big.png
  src/Pages/PlaceList/PlaceListItem.jsx
Labels: Status: 추가 기능 구현중
